# source: https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.0.md#upgrade-from-101-to-102

services:
    # @todo, use this and return typehint
    # https://github.com/rectorphp/rector/blob/master/docs/DynamicRectors.md#change-parameters-type-hinting-according-to-the-parent-type
    Rector\Rector\Dynamic\ReturnTypehintRector:
        $returnTypehintClassAndMethod:
            # class
            'Sylius\Bundle\AdminApiBundle\Model\ClientManager':
                # method
                'findClientByPublicId': '?Sylius\Bundle\AdminApiBundle\Model\ClientInterface'
