# source: https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.0.md#upgrade-from-108-to-109

services:
    # @todo, use this and return typehint
    # https://github.com/rectorphp/rector/blob/master/docs/DynamicRectors.md#change-parameters-type-hinting-according-to-the-parent-type
    Rector\Rector\Dynamic\ReturnTypehintRector:
        $returnTypehintClassAndMethod:
            # class
            'Sylius\Bundle\CoreBundle\Templating\Helper\VariantResolverHelper':
                # method
                'resolveVariant': '?Sylius\Component\Product\Model\ProductVariantInterface'
